import type { Anime, LibraryEntry } from "./types";

export const STITCH_ASSETS = {
  avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBA38VzzAqR1PW-ll9TUrmmnQ8gbIXQS1VthXr3Ub60Re0iEUT23_OoWDEihtIresRgGePPTNsMpkV9MQyf-PT1-qv_tdTEZoQ712USRORYNxQFCp2nTqcYZiq4tjPRHqBvkorTOvpWm7DdpHvcdoVWlj9aEzYtlXhsO6EAV_4tEMwuxglM3MLaOvFyfWqucsgw8QHLb2AqAnNEd_nyk8ro0UuMvbVTXz7fQ9prQ6o4DgytZJCPFRRADA",
  loginBackground: "https://lh3.googleusercontent.com/aida-public/AB6AXuC3AhmeQrCq4Y49I90sP0vYP_S-IUb2wR6PqhOLIDJR9aZbl0IiQxmr76JfkpMWrwOo5JLHCaXl3ywcYsFekyCssXBPUcHVDGcZo6QpFRrldacH2o43hDoiuKI5qidAKnLgkC27bt78q0ti97fzW9SALk3YAcIhTh13tCzeGHHYdlClgR52tyBEyjUCSifwuHRLJ_HW35fN8EdRkWCXBw0z_d9-9xRrgYO-DVxvcknYTSWhBo1bWU0zxQ",
  dashboardHero: "https://lh3.googleusercontent.com/aida-public/AB6AXuA2grLAOVTfsBE1KYqAKSKp-4sAFtAVvLtAaFRppV4yhmBSU0Ot5rN2acfUL2KFEluPhzs1LIvymAiF8d9TOQGxoraEf6OL2MZwJUN8ASXuy-YNT8A4lVAJiEyMGQ4CHkscGTZQ8XmRmQebCONALx6HpKb_I57ONbg0nrcf2OwbZJDip-K_oARny_hX4Tbl7yzgmSlV3zywyIj38jdGSuL0n0XUPS6SiLZ3uGwUfsccIH_bKKTmsU6Ktg",
  player: "https://lh3.googleusercontent.com/aida-public/AB6AXuCPhrWJmmzzPBwjjk7HOsYq7Iuv2sT58yLRAaNNsghEB3UbOSlxRIeyGMvjiXNjegD9xu9AjveqXKa2Jhz0923LkXfQhamaK7x0ozOZoKZC8b2YWo4i1gInz7-NPiGe-0vCyxlfRQl8NY4Ko8Y41InvS4wHScLBv9hkI8gQFlsxd4aZYpnubwxLtV1AFRFKxz60WYVVFYkxbXWJEe59L8-4KVHef1YPP_9qS7W5gSX4bonDa-PEgN-T4w",
  episodeOne: "https://lh3.googleusercontent.com/aida-public/AB6AXuB5pQzpmiuBwz4CUNaWXQdfmO0QpzWHCclt9SrFVBnWkFAE1W4DhXWbws6jU58tNGtUQE3_MErSXmVMSLpl3SPg9Fy6XridFWa8BrDzAm1zMmAvwlyfArvLJaHQVEMCtEjxcTMnEu7b8UiCZbngyxyW5W4SjNCje2UBKpCwNU1W4CRZJP7G1tMIRu9AJWwKY9rKPhkwi2D94DDTEMEYxSiwlqYLSQN7ltUnLB18J-i-RnI0jkz0nXLDwg",
  episodeTwo: "https://lh3.googleusercontent.com/aida-public/AB6AXuCCt3G4lfiOdA76Rod9rRJ6myQihjlylvu5wsWiUiL2aZJ4rTreAhOrETKIB3phVW4EMRxRiDgC8ZnJ5hojuBfU-hO2r8crDZZUhr5i-z_D4rbL9MjeLibbt9QbDVhJinl512L8g_151ahNF3I1S-zxiBFBAyVisNf_YtTlsiDWIfowVNKCWPBSq3kMRirf_gMGDSbnenSg2nMU6rV91XtfWT7O192kphUah65XqoK8RkIw6doazpMG7A",
  episodeThree: "https://lh3.googleusercontent.com/aida-public/AB6AXuAxqUbrsb_EI5xAEb2SrR3vFJgsEJqgpkYIOMMSYPl0qJfeRQOOFbM2vI66KKrkE7umoFX0BNmvxmE7Voh86ZB_5ZyOSUBsyD2A3SZfzoQY2HojfTIzLGIs0uUMANlGHttM1SzkfwGS3nrz_Qg5zlMYHo7kR7dFMxSa_lsTReXmU1xChsRmdHFK_ZU3Xf_BQhH6fvw0RK_SCfzzf36-8vwxO7v9rgEo0DwZl54dLiluIBaK5suuxQ-80A",
  wanderingWitch: "https://lh3.googleusercontent.com/aida-public/AB6AXuCi5FAu6u79mTBLXSUIW-uueutqFkSYQPIt_BpJiKiCDj62BDHQ3apTZd3eAArtKq4W-IUuXvP3JYX-IErLWQb6rUKdfb-g79Ps2Am2FpXpRfyHhvKuQG2B1GniwkYPE8iJX3QsVltFe6A-bfZumBiwm3MbXM7UVkrCELGenDmwQgHu1arla2630DkDHJQh1kyOfoQzNY5lfrrdeV71P_UJp6clkh57ltN_NZeZUx-w9W0EKBtx-NVE4g",
  spiceWolf: "https://lh3.googleusercontent.com/aida-public/AB6AXuCDmI4SV1A-iN2tJN6b5wqwzU0akRqnoUa846X3cVUbzvDR7kA-ziFHhXmh9KAKle6nO2sIsZOilduUZSjWBtFGhznoi2ERQCtCJedfEdHdmNMlHb0Z5ZurqutJq-yjSbsCKMvipR2pw9mc11F1jJaJ305ejHHB6WnTvfEIjyYFVqkuHb_V07ii8mw-swDFwF64uWLbcbMvXWSN1AmigLF4PEkkNPjt9JsDZ9YSetvd9qHcLLFPgzSSpA",
} as const;

export const ANIME_CATALOG: Anime[] = [
  { id: "skyward-bloom", title: "Frieren: Beyond Journey's End", subtitle: "Sousou no Frieren", synopsis: "After the party of heroes defeated the Demon King, the elven mage Frieren comes face to face with humanity's mortality and begins a new journey.", genres: ["Adventure", "Drama", "Fantasy"], totalEpisodes: 28, episodeMinutes: 24, accent: "violet", score: "9.14", coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDBIDocqcNKZ6uYAM4-fAxK0oAXAQnBBx6V-thJqBW64weYH3mYqC-vQAA1kYbpPw3s-N9h-5WaaMJ90TU4HysiGq8TbPvUjs_Gi7PfZZWFGDpxorgRkyyCN8l18MGt1xke5cqwL445AzvpKMPbjRmRimUd-IoY7DAeHI7lbgNtCP9o-jU8VWqhck6wOrvrEl48Etp-Gh4uwbIp4qcKa4mYxXjXY0KMo4ptk-d5PvuNj1LgqZo9QE7Q0Q", heroUrl: STITCH_ASSETS.dashboardHero },
  { id: "neon-requiem", title: "Cyberpunk: Edgerunners", subtitle: "Cyberpunk", synopsis: "A street kid tries to survive in a technology-obsessed city by becoming an edgerunner.", genres: ["Action", "Sci-fi"], totalEpisodes: 10, episodeMinutes: 24, accent: "cyan", score: "8.6", coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuD1oDtw2Us7HQO3bFqLBrC-Fn1cPE4wDEZOAUpCp8UBxR1RiC4Me2OqfrGk9uYJgzDfpIOGFXSBrtRLMenJz7pRmtvahXEIl0-fKOowIxngUodM2Jbh_qJXW-k6bCzxJ1s8kR7l_CL1Nb1mkNNmWBo5ypWx_QNwIcncFLHaY5z6FzCKuJ92TAuOdAlRrMsj2xh0eQ7OZYnVEK3A2UjWKV9MY1hMe4-LEWSrKfuLw3cLXbo3xuB8APPBmw" },
  { id: "moonlit-recipe", title: "Mushoku Tensei S2", subtitle: "Jobless Reincarnation", synopsis: "A second chance at life unfolds across a richly imagined fantasy world.", genres: ["Fantasy", "Drama"], totalEpisodes: 24, episodeMinutes: 24, accent: "rose", score: "8.5", coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDxdrMakJgn0vhC5ilVcvkFl8Fn1tI5daEdIYw26mC5ic3hpetOX9PUBIXHv1jfwvlie7IUMdhuzByo3n3Lt-B7ZusFX4bMKNNC7hTRiHWflC7YDzzwK1IM05RU1HGzwHtV031G6dlfcdxj86kN_51sR7tHIO60J7-kvZ1RlRk6NbPcBH2x8GpZ7z92Z47G8EdV5ZbyPGFQB_p9KWxap1lXYOXny7pwNRHqezJhUptkqhusyY6rl0cG7Q" },
  { id: "constellation-code", title: "Jujutsu Kaisen Season 2", subtitle: "Hidden Inventory", synopsis: "Sorcerers confront a past that will reshape the jujutsu world.", genres: ["Action", "Supernatural"], totalEpisodes: 23, episodeMinutes: 24, accent: "indigo", score: "8.8", coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDe9EwVTOlQOLeztsXNpN3ci25h2lZSf6B7qpy27f_tpNgDjh0xEI8X7Jmh-mrpFIV1rE3UF_giOhuesxTxVZ11DX_1j1ZN56yet2kfe_LLiLZBJAFoF3_NbwjnX4dNN8nAsIHx3clvaOMLfpmTFm83q1-g15xSeXFrL4W9_cvsfdjSlL3xtZ87u5FlJUEzfd8964F4rhuMtJsydLuMOPpqBROBgFegaPMj5WTxzdHMrZwQ_mo_4ElmuQ" },
  { id: "last-shrine", title: "Demon Slayer: Hashira Training Arc", subtitle: "Kimetsu no Yaiba", synopsis: "Tanjiro trains with the Hashira ahead of the final battle.", genres: ["Action", "Fantasy"], totalEpisodes: 8, episodeMinutes: 24, accent: "amber", score: "8.4", coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBEPtKHsKdL9qiFB8ZnPYfvEETLjKa4OzvznqnpuRaKrzKA9sUy8SISD8OTYo-LVf1hRVt-WA3hweKrgzVSMQnP3rc_MHCQA5uEarMrMgr-2_slqFWvUVfFdvi1Gy2nZ-4mADP8wzf3kO1IRBJL6PMTJ2A0BkcDF9ZEumU2LUCfOjm61PXq8oJWSpD_WKLeCGa_Llf9aMf5uzIidJismYVUAVf4HceWUVnPeN8mj5_6QgSROujcdzP7Yg" },
  { id: "harbor-of-wishes", title: "The Eminence in Shadow", subtitle: "Shadow Garden", synopsis: "A mastermind in the shadows builds the secret organization of his dreams.", genres: ["Action", "Comedy"], totalEpisodes: 20, episodeMinutes: 24, accent: "emerald", score: "8.2", coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBqDVco59NNlXeychHF16GqqFyw7w97vWBYTT4chs9nOg8K4lCdO6qotbFqRzbVMU1mLewzrRjZlg5dGGXsuC-Qz3LYuon8SlYPC129ZssckWHW0AHde6am3ewyYgm-00APaW89efxBbdolXfSWHP66eF1mhRZmruhb3O1ikNGR8oy7AD1yu8jEaEhtd0XF0dmdgJOLTk2NAyWnFnZHtnGWS3epAF-357cehiZPOkwUWQ8X5VCOBMeDEA" },
];

export function getAnimeById(animeId: string) {
  return ANIME_CATALOG.find((anime) => anime.id === animeId);
}

export function createSeedLibrary(): Record<string, LibraryEntry> {
  return {
    "skyward-bloom": { animeId: "skyward-bloom", status: "watching", watchedEpisodes: 12, currentEpisode: 14, playbackSeconds: 863, updatedAt: "2026-08-30T08:42:00.000Z" },
    "neon-requiem": { animeId: "neon-requiem", status: "watching", watchedEpisodes: 7, currentEpisode: 8, playbackSeconds: 0, updatedAt: "2026-08-29T14:10:00.000Z" },
    "moonlit-recipe": { animeId: "moonlit-recipe", status: "watching", watchedEpisodes: 8, currentEpisode: 9, playbackSeconds: 198, updatedAt: "2026-08-28T19:22:00.000Z" },
    "constellation-code": { animeId: "constellation-code", status: "planned", watchedEpisodes: 0, currentEpisode: 1, playbackSeconds: 0, updatedAt: "2026-08-27T06:45:00.000Z" },
    "last-shrine": { animeId: "last-shrine", status: "completed", watchedEpisodes: 8, currentEpisode: 8, playbackSeconds: 0, updatedAt: "2026-08-24T12:30:00.000Z" },
    "harbor-of-wishes": { animeId: "harbor-of-wishes", status: "planned", watchedEpisodes: 0, currentEpisode: 1, playbackSeconds: 0, updatedAt: "2026-08-22T15:08:00.000Z" },
  };
}
